version: '3'
services:
  fndr-web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - PORT=8000
