version: '3'
services:
  redis-server:
    image: 'redis'
    ports:
      - '6380:6379'
  fndr-web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/fndr-web:cached
      - /usr/fndr-web/node_modules
    env_file:
      - .env
    environment:
      - LOGGING_LEVEL=debug
      - PORT=8000
      - REDIS_URL=redis://redis-server:6379
